ELEVATE-Project/mentoring

src/api-doc/MenterEd.postman_environment.json
src/api-doc/MentorED-Mentoring.postman_collection.json

Added Postman collection

---

src/db/sessions/model.js
src/services/helper/feedback.js
src/services/helper/sessions.js

Resolved Story

---

src/api-doc/api-doc.yaml
src/globalConfig.json
src/test/mentees.spec.js
src/test/mentors.spec.js

Added test cases for education qulification

Added test cases for education qulification

---

src/api-doc/MentorED-Mentoring.postman_collection.json
src/api-doc/api-doc.yaml
src/controllers/v1/mentors.js
src/db/sessions/queries.js
src/locales/en.json
src/services/helper/mentors.js

Added mentors upcoming session

Added mentors upcoming session

---

src/globalConfig.json
src/services/helper/mentors.js

fixed share profile api

---

src/controllers/v1/mentees.js
src/services/helper/mentees.js

fixed home feed problem

---

src/db/sessions/queries.js

Fixed Sort Data

---

src/middlewares/pagination.js

search test fixed

---

src/services/helper/form.js

fixed caching problem of form

---

src/globalConfig.json
src/middlewares/pagination.js

Fixed special char

---

src/controllers/v1/sessions.js
src/db/sessions/model.js
src/db/sessions/queries.js
src/globalConfig.json
src/middlewares/pagination.js
src/services/helper/mentors.js
src/services/helper/sessions.js
src/services/helper/userProfile.js
src/test/session.spec.js

Fixed Mentor Name

---

src/db/sessionAttendees/queries.js
src/globalConfig.json
src/services/helper/mentees.js

Fixed Mentee Home page mentor Name

Fixed Mentee Home page mentor Name

---

src/db/sessions/queries.js
src/globalConfig.json
src/services/helper/mentees.js
src/services/helper/mentors.js
src/services/helper/sessions.js

Moved caching from mentoring to user side and reused codes

Moved caching from mentoring to user side and reused codes

---

src/globalConfig.json
src/services/helper/mentees.js
src/services/helper/mentors.js

Fixed circular dependancy

---

src/generics/utils.js
src/globalConfig.json

fixed form update issue

---

src/db/sessions/queries.js
src/services/helper/mentees.js

fixed date sorting bug

---

src/db/sessions/queries.js
src/globalConfig.json

fixed date sorting

---

src/api-doc/api-doc.yaml
src/globalConfig.json
src/locales/en.json

fixed uppercase spelling mistake

fixed uppercase spelling mistake

---

src/.env.sample
src/globalConfig.json

added kafka topic

---

src/.env.sample
src/envVariables.js
src/globalConfig.json

added env variables

---

src/services/helper/feedback.js

fixed bug-454

---

src/.env.sample
src/envVariables.js
src/services/helper/bigBlueButton.js

Done with big blue button

---

src/db/forms/queries.js
src/test/mentees.spec.js
src/test/mentors.spec.js

Form Data changes

---

src/api-doc/MentorED-Mentoring.postman_collection.json
src/api-doc/api-doc.yaml
src/services/helper/form.js
src/test/forms.spec.js
src/test/mentees.spec.js
src/test/mentors.spec.js

added api doc and updated postman collection

added api doc and updated postman collection

---

src/db/entities/model.js
src/db/forms/model.js
src/db/issues/model.js
src/db/notification-template/model.js
src/db/questions/model.js
src/db/questionsSet/model.js
src/db/sessionAttendees/model.js
src/db/sessions/model.js
src/db/sessions/queries.js
src/package.json
src/services/helper/feedback.js

added lean plugin to all services

added lean plugin to all services

---

src/services/helper/sessions.js

Added two keys for joined and enrolled

Added two keys for joined and enrolled

---

src/database/migrations/20231123143104-add-createdby-and-updated-by-org-extension.js
src/database/models/organisationExtension.js
src/services/org-admin.js

Fixed an issue with getOrgPolicies [2407.4]
Added created by and updated by fields to organization extension [2407.6]

Fixes based on task 2407

---

src/services/form.js

Avoiding modification of partition value (organization_id) in form table, API: form/update

Avoiding modification of partition value[BUG:1169]

---

src/services/sessions.js

Fix :  Duration should be rounded off to specific time, for example(60.55555 indicates 61 and 60.22222 indicates 60)

[Bug - 1187]Round off Applied To Session Duration Passed to the Mail

---

src/services/sessions.js

Session title was passed instead of session type to the edit notification mail template. This PR will resolve the issue

[BUG-1216] Bug Fix For Passing Session Type

---

src/services/sessions.js

Fix for bug [1217](https://katha.shikshalokam.org/bug-view-1217.html)

fixed an issue with /enroll API

---

src/services/sessions.js

Not exactly related to reported bug - incorrect boolean was getting passed to the saas check function
https://katha.shikshalokam.org/bug-view-1245.html

[Bug 1245] Related fix

---

src/services/mentors.js

Ticket Id : https://katha.shikshalokam.org/bug-view-1266.html
Change : sending status as value labels in the response, as requested by Front end.

[Bug-1266] : Processing Entity Types To Add Value Labels

---

src/services/sessions.js

fix for https://katha.shikshalokam.org/bug-view-1242.html

added meeting link for session creator

---

src/services/sessions.js

Fix for https://katha.shikshalokam.org/bug-view-1218.html.

updated enroll and unenroll functions to skip count update for SM

---

src/services/mentors.js
src/services/users.js

fix for https://katha.shikshalokam.org/bug-view-1337.html

fix: an issue with mentor visibility policy

---

src/locales/en.json
src/services/org-admin.js
src/services/sessionInvite.js

I have updated date for future dates also we can create sessions

Issue for csv uploading

---

src/constants/common.js
src/services/sessionInvite.js

Keyword for Google meet is breaking the edit flow for googleMeet link

QA Issue changes - 1342

---

src/validators/v1/entity.js

Removing regex validation for label

---

interface-routes/sunbird-mentoring.json

Reverts ELEVATE-Project/mentoring#1138

Revert "Update sunbird-mentoring.json"

---

src/middlewares/authenticator.js

Reverts ELEVATE-Project/mentoring#1191

Revert "Update authenticator.js"

---

interface-routes/elevate-mentoring.json

Reverts ELEVATE-Project/mentoring#1205

Revert "Update elevate-mentoring.json"
